<sentence> := <subject>" "<predicate>
<subject> := <article>" "<noun>|<noun>
<predicate> := <verb>" "<directObject>
<directObject> ::= <article>" "<noun>
<article> := "THE" | "A"
<noun> := "MAN" | "DOG"
<verb> := "BITES" | "PETS"
