<sentence> := <subject> <predicate>
<subject> := <article> <noun>
<predicate> := <verb> <directObject> 
<directObject> ::= <article> <noun>
<article> := THE | A
<noun> := MAN | DOG
<verb> := BITES | PETS
<a> := regex(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)
